// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJUy_UT4IPSugtsJz6_I73XvRRRcxFqoc',
    appId: '1:327642350514:web:31165046211acf5cad5aab',
    messagingSenderId: '327642350514',
    projectId: 'nekiapp-52446',
    authDomain: 'nekiapp-52446.firebaseapp.com',
    storageBucket: 'nekiapp-52446.firebasestorage.app',
    measurementId: 'G-QSLJXVVEKH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxVai6C944stx2xQeQsJ56Yd_RK6Cz1cc',
    appId: '1:327642350514:android:c344e9d50c718a40ad5aab',
    messagingSenderId: '327642350514',
    projectId: 'nekiapp-52446',
    storageBucket: 'nekiapp-52446.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALbSJyHKBm_RG_SX8aL8yjRGnIoyvy3Iw',
    appId: '1:327642350514:ios:88a40cc0bfa17f6ead5aab',
    messagingSenderId: '327642350514',
    projectId: 'nekiapp-52446',
    storageBucket: 'nekiapp-52446.firebasestorage.app',
    androidClientId: '327642350514-cm6v8dnv23lco9rksoonas7msq5nkd8u.apps.googleusercontent.com',
    iosClientId: '327642350514-krd0s9jo4bp5ukjo2u6vv72db3knaqkk.apps.googleusercontent.com',
    iosBundleId: 'com.clearwavesystems.nekiapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALbSJyHKBm_RG_SX8aL8yjRGnIoyvy3Iw',
    appId: '1:327642350514:ios:88a40cc0bfa17f6ead5aab',
    messagingSenderId: '327642350514',
    projectId: 'nekiapp-52446',
    storageBucket: 'nekiapp-52446.firebasestorage.app',
    androidClientId: '327642350514-cm6v8dnv23lco9rksoonas7msq5nkd8u.apps.googleusercontent.com',
    iosClientId: '327642350514-krd0s9jo4bp5ukjo2u6vv72db3knaqkk.apps.googleusercontent.com',
    iosBundleId: 'com.clearwavesystems.nekiapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJUy_UT4IPSugtsJz6_I73XvRRRcxFqoc',
    appId: '1:327642350514:web:9e50c057fddad930ad5aab',
    messagingSenderId: '327642350514',
    projectId: 'nekiapp-52446',
    authDomain: 'nekiapp-52446.firebaseapp.com',
    storageBucket: 'nekiapp-52446.firebasestorage.app',
    measurementId: 'G-DETR0BPJE5',
  );

}