// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxVai6C944stx2xQeQsJ56Yd_RK6Cz1cc',
    appId: '1:327642350514:android:52d30e36fa5b431bad5aab',
    messagingSenderId: '327642350514',
    projectId: 'nekiapp-52446',
    storageBucket: 'nekiapp-52446.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALbSJyHKBm_RG_SX8aL8yjRGnIoyvy3Iw',
    appId: '1:327642350514:ios:14cf37855b94e19dad5aab',
    messagingSenderId: '327642350514',
    projectId: 'nekiapp-52446',
    storageBucket: 'nekiapp-52446.firebasestorage.app',
    androidClientId: '327642350514-cm6v8dnv23lco9rksoonas7msq5nkd8u.apps.googleusercontent.com',
    iosClientId: '327642350514-hdjck04tcgkq8e4aijrj8qvob9s23lj9.apps.googleusercontent.com',
    iosBundleId: 'com.clearwavesystems.nekiapp',
  );
}
